name: 'deploy-gcloud-endpoints'
author: 'qinnolabs <contact@qinnolabs.com>'
description: 'creates endpoints configuration and ESPv2 Docker image from OpenAPI document'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'index.js'